ЗАДАНИЕ 3
VADIM33RUS/Project pull request #3
Opened 2019-06-03 16:15 UTC by VADIM33RUS

2019-06-04 08:46 UTC, troepolik requested changes

2019-06-04 08:46 UTC, troepolik commented on QUEST/DB.cs
> +        public void Output()
что это за метод? для чего он нужен?

2019-06-04 08:46 UTC, troepolik commented on QUEST/DB.cs
> +        public void GetValue(List<Plane> Spisok)
что это за метод со странным названием? ни комментариев, ничего...
почему возвращаемое значение передается как параметр?

2019-06-04 08:46 UTC, troepolik commented on QUEST/DB.cs
> +                        switch (reader.GetValue(2))
вместо индексированного обращения в ридере лучше использовать именованное, т.к если изменится запрос, то поедут индексы + непонятно что это мы получаем по этому индексу

2019-06-04 08:46 UTC, troepolik commented on QUEST/DB.cs
> +                                    Spisok.Add(new Plane_fighter(reader));
лдучше заюзать конструктор по умолчанию + метод Serialize  для созданного объекта

2019-06-04 08:46 UTC, troepolik commented on QUEST/Plane.cs
> +            Wingspan = Convert.ToInt32(reader.GetValue(3));
использовать именованное обращение к полям в ридере,, типа reader ["Name"]

2019-06-04 08:46 UTC, troepolik commented on QUEST/Plane.cs
> +            Name = reader.GetValue(1).ToString();
даблкод, что мы проходили во 2й лабе, видимо использовать не научились)

2019-06-04 08:46 UTC, troepolik commented on QUEST/Program.cs
> +                new Plane_carrier("ЛИ-2", 4, false, 290, 29.98)
вроде как по условиям лабы мы этот хардкод убираем и вместо этого заполняем список из базы

2019-06-04 08:46 UTC, troepolik commented on QUEST/Program.cs
> +                DB Db = new DB();
а кто коннекшен потом закроет?

2019-06-04 08:46 UTC, troepolik commented on QUEST/Program.cs
> +            catch (Exception ex)
я хочу дополнителдьно отдельню обработку SqlException

2019-06-04 08:46 UTC, troepolik commented on QUEST/Program.cs
> +                Console.WriteLine(ex.StackTrace);
лучше заюзать ex.ToString()

2019-06-04 13:08 UTC, troepolik requested changes

2019-06-04 13:08 UTC, troepolik commented on QUEST/DB.cs
> +        public void GetValue(List<Plane> Spisok)
так и не поправили

2019-06-04 13:08 UTC, troepolik commented on QUEST/DB.cs
> +        public void Output()
так и не убрали

2019-06-04 13:08 UTC, troepolik commented on QUEST/DB.cs
> +            command.Dispose();//Этой командой мы говорим, что больше объект использоваться нами не будет
использовать вместо этого конструкцию  using

2019-06-04 13:08 UTC, troepolik commented on QUEST/Plane.cs
> +            Name = reader["Name"].ToString();
даблкод

2019-06-04 13:08 UTC, troepolik commented on QUEST/Program.cs
> +            catch (Exception ex)
так и не поправили

2019-06-05 12:14 UTC, VADIM33RUS commented on QUEST/Plane.cs
> +            Name = reader["Name"].ToString();
Переместил в Plane

2019-06-05 13:42 UTC, troepolik requested changes

2019-06-05 13:42 UTC, troepolik commented on QUEST/DB.cs
> +        public List<Plane> GetValue()
называть методы нужно правильно типа GetPlanes

2019-06-05 13:42 UTC, troepolik commented on QUEST/DB.cs
> +            using (SqlCommand command = new SqlCommand(@"SELECT Id,Name,Type,Weapons,Wingspan,Speed,RLS FROM [Table]", connect))
называть таблицу Table  это как-то не серьезно... назови её по смыслу.

2019-06-05 13:42 UTC, troepolik commented on QUEST/DB.cs
> +                        if (reader.HasRows)
лишняя проверка.

2019-06-05 13:42 UTC, troepolik commented on QUEST/DB.cs
> +                            switch (reader.GetValue(2))
обращение по индексу- потенциально упадет если изменится набор столбцов или запрос

2019-06-05 13:42 UTC, troepolik commented on QUEST/DB.cs
> +                                        Spisok.Add(new Plane_fighter(reader));
я не хочу чтобы конструктор принимал Reader.  я хочу конструктор по умолчанию + метод Serialize

2019-06-05 13:42 UTC, troepolik commented on QUEST/Plane.cs
> +            Wingspan = Convert.ToDouble(reader["Wingspan"]);
хорошо, но я так и не увидел где у тебя сериализуются поля наследников?
например есть наследник от Plane  и у него 2 дополнительных поля. где их сериализация?

2019-06-05 13:42 UTC, troepolik commented on QUEST/Program.cs
> +            //catch (Exception ex)
нет, я хочу чтобы обычные ошибки тоже обрабатывались. просто при скл-ных в лог можно писать что-то особенное. короче цель- разделить обработку ошибок.

2019-06-06 11:58 UTC, troepolik requested changes

2019-06-06 11:58 UTC, troepolik commented on QUEST/DB.cs
> +                        plane.Last().Serialize(reader);
зачем каждый раз его искать? на итерации ты всегда знаешь что создаешь и что нужно сериализовать.

2019-06-06 11:58 UTC, troepolik commented on QUEST/DB.cs
> +                                        plane.Add(new Plane_carrier());
добавление в список можно вынести из кейза

2019-06-06 13:09 UTC, VADIM33RUS commented on QUEST/DB.cs
> +                        plane.Last().Serialize(reader);
Хорошо, учту

2019-06-12 15:19 UTC, troepolik approved these changes

2019-06-12 15:19 UTC, merged